In [2]:
import pandas as pd
import openpyxl

In [28]:
data = "Desktop/GerardoIga/2025/Celegans/CPLZ08292402-2_negative data.xlsx"

df = pd.read_excel(data)

In [29]:
df

,No,LipidIon,LipidGroup,Class,FattyAcid,FA1,FA2,FA3,CalcMz,ObsMz,...,ED3,LW1,LW2,LW3,LN1,LN2,LN3,LE1,LE2,LE3
0,1,BiotinylPE(17:4)-H,BiotinylPE(17:4)-H,BiotinylPE,(17:4),(17:4),NaN,NaN,698.288181,698.28818,...,5.598193e+05,3.241879e+05,3.342377e+05,2.246472e+05,8.373872e+05,2.937244e+05,5.741149e+05,3.953384e+05,2.035308e+06,8.967286e+05
1,2,BiotinylPE(29:0)-H,BiotinylPE(29:0)-H,BiotinylPE,(29:0),(29:0),NaN,NaN,874.538581,874.53858,...,6.187273e+05,6.017536e+06,4.946070e+06,2.261614e+06,1.511098e+06,3.430637e+06,3.695453e+06,6.534651e+05,5.975092e+05,7.602397e+05
2,3,BiotinylPE(31:0)-H,BiotinylPE(31:0)-H,BiotinylPE,(31:0),(31:0),NaN,NaN,902.569881,902.56988,...,1.806647e+05,5.179091e+06,3.355959e+06,1.741735e+06,9.502546e+05,2.516269e+06,3.005312e+06,9.674704e+04,1.230563e+05,1.883715e+05
3,4,BiotinylPE(31:1)-H,BiotinylPE(31:1)-H,BiotinylPE,(31:1),(31:1),NaN,NaN,900.554231,900.55423,...,5.290517e+04,5.870855e+05,2.384036e+06,5.499062e+05,7.977391e+05,7.882101e+05,1.343165e+06,2.916778e+05,5.483816e+04,2.482264e+05
4,5,BiotinylPE(31:2)-H,BiotinylPE(31:2)-H,BiotinylPE,(31:2),(31:2),NaN,NaN,898.538581,898.53858,...,6.010721e+04,1.807777e+06,2.400740e+06,1.134690e+06,5.280464e+05,8.625769e+05,1.180132e+06,1.701322e+05,3.587863e+04,7.231706e+04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1298,1299,dMePE(40:8+OO)-H,dMePE(40:8+OO)-H,dMePE,(40:8+OO),(40:8+OO),NaN,NaN,846.529061,846.52906,...,0.000000e+00,2.531559e+06,4.835344e+05,2.053372e+06,6.748116e+05,6.972259e+05,7.540934e+05,3.835034e+05,1.321995e+06,1.845150e+05
1299,1300,dMePE(44:1)-H,dMePE(44:1)-H,dMePE,(44:1),(44:1),NaN,NaN,884.711381,884.71138,...,2.898482e+05,1.487704e+06,1.241927e+06,4.028423e+05,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,4.031408e+05
1300,1301,phSM(d19:0_16:1)+HCOO,phSM(d35:1)+HCOO,phSM,(d19:0_16:1),(d19:0),(16:1),NaN,777.576345,777.57634,...,8.415979e+04,1.572032e+06,8.420498e+05,2.785517e+06,1.832359e+06,1.355600e+06,2.139183e+06,2.047917e+06,1.776615e+06,1.055186e+06
1301,1302,phSM(d19:0_18:1)+HCOO,phSM(d37:1)+HCOO,phSM,(d19:0_18:1),(d19:0),(18:1),NaN,805.607645,805.60764,...,1.475738e+06,1.197755e+07,6.660458e+06,1.526956e+07,1.022941e+07,1.220147e+07,1.233998e+07,1.301337e+07,1.146920e+07,8.587201e+06
1302,1303,phSM(t41:0)+HCOO,phSM(t41:0)+HCOO,phSM,(t41:0),(t41:0),NaN,NaN,879.680810,879.68081,...,2.060061e+06,1.864975e+07,1.163470e+07,2.152489e+07,1.994717e+07,1.877844e+07,2.106428e+07,4.632783e+07,3.952904e+07,3.509816e+07

In [30]:
df.shape

(1303, 33)

In [31]:
df_filt = df.loc[df.groupby('LipidIon')['Rt'].idxmax()]

In [32]:
df_filt.head(10)

,No,LipidIon,LipidGroup,Class,FattyAcid,FA1,FA2,FA3,CalcMz,ObsMz,...,ED3,LW1,LW2,LW3,LN1,LN2,LN3,LE1,LE2,LE3
0,1,BiotinylPE(17:4)-H,BiotinylPE(17:4)-H,BiotinylPE,(17:4),(17:4),NaN,NaN,698.288181,698.28818,...,5.598193e+05,3.241879e+05,3.342377e+05,2.246472e+05,8.373872e+05,2.937244e+05,5.741149e+05,3.953384e+05,2.035308e+06,8.967286e+05
1,2,BiotinylPE(29:0)-H,BiotinylPE(29:0)-H,BiotinylPE,(29:0),(29:0),NaN,NaN,874.538581,874.53858,...,6.187273e+05,6.017536e+06,4.946070e+06,2.261614e+06,1.511098e+06,3.430637e+06,3.695453e+06,6.534651e+05,5.975092e+05,7.602397e+05
2,3,BiotinylPE(31:0)-H,BiotinylPE(31:0)-H,BiotinylPE,(31:0),(31:0),NaN,NaN,902.569881,902.56988,...,1.806647e+05,5.179091e+06,3.355959e+06,1.741735e+06,9.502546e+05,2.516269e+06,3.005312e+06,9.674704e+04,1.230563e+05,1.883715e+05
3,4,BiotinylPE(31:1)-H,BiotinylPE(31:1)-H,BiotinylPE,(31:1),(31:1),NaN,NaN,900.554231,900.55423,...,5.290517e+04,5.870855e+05,2.384036e+06,5.499062e+05,7.977391e+05,7.882101e+05,1.343165e+06,2.916778e+05,5.483816e+04,2.482264e+05
4,5,BiotinylPE(31:2)-H,BiotinylPE(31:2)-H,BiotinylPE,(31:2),(31:2),NaN,NaN,898.538581,898.53858,...,6.010721e+04,1.807777e+06,2.400740e+06,1.134690e+06,5.280464e+05,8.625769e+05,1.180132e+06,1.701322e+05,3.587863e+04,7.231706e+04
5,6,BiotinylPE(31:3)-H,BiotinylPE(31:3)-H,BiotinylPE,(31:3),(31:3),NaN,NaN,896.522931,896.52293,...,9.958308e+04,4.169257e+06,3.561374e+06,1.495063e+06,6.617896e+05,6.361028e+05,2.827563e+05,1.983494e+05,6.976259e+04,2.509609e+05
6,7,BiotinylPE(32:0)-H,BiotinylPE(32:0)-H,BiotinylPE,(32:0),(32:0),NaN,NaN,916.585531,916.58553,...,1.773587e+06,2.706991e+06,9.262999e+05,2.272501e+06,1.315782e+06,9.628699e+05,1.632864e+06,1.343162e+06,1.051813e+06,4.292432e+05
7,8,BiotinylPE(32:2)-H,BiotinylPE(32:2)-H,BiotinylPE,(32:2),(32:2),NaN,NaN,912.554231,912.55423,...,0.000000e+00,5.413719e+06,5.287470e+06,2.654610e+06,1.450207e+06,2.171770e+06,2.538110e+06,3.097784e+05,2.583521e+05,4.662873e+05
8,9,BiotinylPE(32:3)-H,BiotinylPE(32:3)-H,BiotinylPE,(32:3),(32:3),NaN,NaN,910.538581,910.53858,...,3.015674e+05,2.748834e+06,4.558011e+06,2.611926e+06,2.836545e+06,3.630744e+06,3.777496e+06,1.028224e+06,9.337894e+05,1.521777e+06
10,11,BiotinylPE(33:2)-H,BiotinylPE(33:2)-H,BiotinylPE,(33:2),(33:2),NaN,NaN,926.569881,926.56988,...,1.514463e+05,5.880159e+06,4.366302e+06,3.029006e+06,1.725155e+06,2.852181e+06,2.691846e+06,7.187318e+05,4.806967e+05,9.693639e+05

In [12]:
#option2

df_sorted = df.sort_values(by='Rt', ascending=False)
df_filt2 = df_sorted.drop_duplicates(subset='LipidIon', keep='first')

In [33]:
df_filt.shape

(899, 33)

In [14]:
df_filt2.head()

,No,LipidIon,LipidGroup,Class,FattyAcid,FA1,FA2,FA3,CalcMz,ObsMz,...,ED3,LW1,LW2,LW3,LN1,LN2,LN3,LE1,LE2,LE3
789,790,PC(12:0_12:0)+HCOO,PC(24:0)+HCOO,PC,(12:0_12:0),(12:0),(12:0),NaN,666.435161,666.43516,...,365996.6970,140427.3036,185761.4022,341686.2760,170901.6290,71271.7287,27632.5980,102144.1812,46763.2230,56744.1255
340,341,LPC(12:0)+HCOO,LPC(12:0)+HCOO,LPC,(12:0),(12:0),NaN,NaN,484.268096,484.26810,...,74615.5440,29470.6410,84677.1258,224363.4560,173225.0890,84647.0870,128196.2330,51844.8027,218292.7880,14277.7521
441,442,LPE(18:0e)-H,LPE(18:0e)-H,LPE,(18:0e),(18:0e),NaN,NaN,466.330301,466.33030,...,261.5440,29805.9183,60628.3650,7651.4883,92817.0393,46769.2020,341216.0490,41695.6878,61522.5072,26736.5853
1247,1248,SPHP(m22:1)+HCOO,SPHP(m22:1)+HCOO,SPHP,(m22:1),(m22:1),NaN,NaN,464.314651,464.31465,...,184096.9881,624886.5190,71007.8250,73771.1370,110920.2855,239707.6914,326720.7222,209765.1890,91814.1267,41005.2105
1232,1233,SPHP(m22:0)+HCOO,SPHP(m22:0)+HCOO,SPHP,(m22:0),(m22:0),NaN,NaN,466.330301,466.33030,...,7017.4944,192504.1434,219988.9767,88693.2747,207063.3570,131320.4481,110245.8816,170555.8887,102212.7276,20946.5688

In [38]:
data2_positive = "Desktop/GerardoIga/2025/Celegans/CPLZ08292402-2_positive data.xlsx"

df2p = pd.read_excel(data2_positive)

df2p.head()

,No,LipidIon,LipidGroup,Class,FattyAcid,FA1,FA2,FA3,CalcMz,ObsMz,...,ED3,LW1,LW2,LW3,LN1,LN2,LN3,LE1,LE2,LE3
0,1,AcCa(15:0)+H,AcCa(15:0)+H,AcCa,(15:0),(15:0),NaN,NaN,386.326485,386.32649,...,644412.185,2321.1080,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
1,2,AcCa(16:0)+H,AcCa(16:0)+H,AcCa,(16:0),(16:0),NaN,NaN,400.342135,400.34214,...,0.000,0.0000,1.057062e+06,2.636818e+06,3.183084e+06,3.996716e+06,5.046420e+06,2.180633e+06,2.291380e+06,2.086173e+06
2,3,AcCa(17:1)+H,AcCa(17:1)+H,AcCa,(17:1),(17:1),NaN,NaN,412.342135,412.34214,...,1137681.002,163450.5650,0.000000e+00,4.140000e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
3,4,AcCa(18:0)+H,AcCa(18:0)+H,AcCa,(18:0),(18:0),NaN,NaN,428.373435,428.37344,...,1509511.076,26130.6786,0.000000e+00,6.161798e+04,0.000000e+00,2.234704e+04,0.000000e+00,7.309596e+03,2.461293e+04,9.145363e+03
4,5,AcCa(18:0)+H,AcCa(18:0)+H,AcCa,(18:0),(18:0),NaN,NaN,428.373435,428.37344,...,0.000,3004.9536,4.654802e+06,1.275543e+07,1.668676e+07,2.053900e+07,2.078996e+07,1.459915e+07,1.601355e+07,1.255348e+07

In [39]:
df2p.shape

(2938, 33)

In [40]:
df2p_2 = df2p.loc[df.groupby('LipidIon')['Rt'].idxmax()]

In [41]:
df2p_2.shape

(899, 33)

In [44]:
df2p_2.head()

,No,LipidIon,LipidGroup,Class,FattyAcid,FA1,FA2,FA3,CalcMz,ObsMz,...,ED3,LW1,LW2,LW3,LN1,LN2,LN3,LE1,LE2,LE3
0,1,AcCa(15:0)+H,AcCa(15:0)+H,AcCa,(15:0),(15:0),NaN,NaN,386.326485,386.32649,...,644412.185,2321.1080,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
1,2,AcCa(16:0)+H,AcCa(16:0)+H,AcCa,(16:0),(16:0),NaN,NaN,400.342135,400.34214,...,0.000,0.0000,1.057062e+06,2.636818e+06,3.183084e+06,3.996716e+06,5.046420e+06,2.180633e+06,2.291380e+06,2.086173e+06
2,3,AcCa(17:1)+H,AcCa(17:1)+H,AcCa,(17:1),(17:1),NaN,NaN,412.342135,412.34214,...,1137681.002,163450.5650,0.000000e+00,4.140000e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
3,4,AcCa(18:0)+H,AcCa(18:0)+H,AcCa,(18:0),(18:0),NaN,NaN,428.373435,428.37344,...,1509511.076,26130.6786,0.000000e+00,6.161798e+04,0.000000e+00,2.234704e+04,0.000000e+00,7.309596e+03,2.461293e+04,9.145363e+03
4,5,AcCa(18:0)+H,AcCa(18:0)+H,AcCa,(18:0),(18:0),NaN,NaN,428.373435,428.37344,...,0.000,3004.9536,4.654802e+06,1.275543e+07,1.668676e+07,2.053900e+07,2.078996e+07,1.459915e+07,1.601355e+07,1.255348e+07