In [5]:
import pandas as pd
%pip install openpyxl
import openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
   ---------------------------------------- 0.0/250.9 kB ? eta -:--:--
   ---- ---------------------------------- 30.7/250.9 kB 660.6 kB/s eta 0:00:01
   ------------------- -------------------- 122.9/250.9 kB 1.8 MB/s eta 0:00:01
   ---------------------------------------  245.8/250.9 kB 2.2 MB/s eta 0:00:01
   ---------------------------------------- 250.9/250.9 kB 1.7 MB/s eta 0:00:00
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

In [7]:
dataPositive = "CPLZ08292402-2_positive data.xlsx"
df_positive = pd.read_excel(dataPositive)

In [10]:
df_positive.head()

,No,LipidIon,LipidGroup,Class,FattyAcid,FA1,FA2,FA3,CalcMz,ObsMz,...,ED3,LW1,LW2,LW3,LN1,LN2,LN3,LE1,LE2,LE3
0,1,AcCa(15:0)+H,AcCa(15:0)+H,AcCa,(15:0),(15:0),NaN,NaN,386.326485,386.32649,...,644412.185,2321.1080,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
1,2,AcCa(16:0)+H,AcCa(16:0)+H,AcCa,(16:0),(16:0),NaN,NaN,400.342135,400.34214,...,0.000,0.0000,1.057062e+06,2.636818e+06,3.183084e+06,3.996716e+06,5.046420e+06,2.180633e+06,2.291380e+06,2.086173e+06
2,3,AcCa(17:1)+H,AcCa(17:1)+H,AcCa,(17:1),(17:1),NaN,NaN,412.342135,412.34214,...,1137681.002,163450.5650,0.000000e+00,4.140000e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
3,4,AcCa(18:0)+H,AcCa(18:0)+H,AcCa,(18:0),(18:0),NaN,NaN,428.373435,428.37344,...,1509511.076,26130.6786,0.000000e+00,6.161798e+04,0.000000e+00,2.234704e+04,0.000000e+00,7.309596e+03,2.461293e+04,9.145363e+03
4,5,AcCa(18:0)+H,AcCa(18:0)+H,AcCa,(18:0),(18:0),NaN,NaN,428.373435,428.37344,...,0.000,3004.9536,4.654802e+06,1.275543e+07,1.668676e+07,2.053900e+07,2.078996e+07,1.459915e+07,1.601355e+07,1.255348e+07

In [18]:
df_positive.shape

(2938, 33)

In [15]:
df_positive_filtered = df_positive.loc[df_positive.groupby('LipidIon')['Rt'].idxmax()]

In [16]:
df_positive_filtered.head(10)

,No,LipidIon,LipidGroup,Class,FattyAcid,FA1,FA2,FA3,CalcMz,ObsMz,...,ED3,LW1,LW2,LW3,LN1,LN2,LN3,LE1,LE2,LE3
0,1,AcCa(15:0)+H,AcCa(15:0)+H,AcCa,(15:0),(15:0),NaN,NaN,386.326485,386.32649,...,6.444122e+05,2321.1080,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
1,2,AcCa(16:0)+H,AcCa(16:0)+H,AcCa,(16:0),(16:0),NaN,NaN,400.342135,400.34214,...,0.000000e+00,0.0000,1.057062e+06,2.636818e+06,3.183084e+06,3.996716e+06,5.046420e+06,2.180633e+06,2.291380e+06,2.086173e+06
2,3,AcCa(17:1)+H,AcCa(17:1)+H,AcCa,(17:1),(17:1),NaN,NaN,412.342135,412.34214,...,1.137681e+06,163450.5650,0.000000e+00,4.140000e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
4,5,AcCa(18:0)+H,AcCa(18:0)+H,AcCa,(18:0),(18:0),NaN,NaN,428.373435,428.37344,...,0.000000e+00,3004.9536,4.654802e+06,1.275543e+07,1.668676e+07,2.053900e+07,2.078996e+07,1.459915e+07,1.601355e+07,1.255348e+07
5,6,AcCa(18:1)+H,AcCa(18:1)+H,AcCa,(18:1),(18:1),NaN,NaN,426.357785,426.35779,...,6.282316e+03,0.0000,5.214563e+06,1.381020e+07,1.670162e+07,2.051538e+07,2.759166e+07,1.006178e+07,1.101308e+07,1.130930e+07
7,8,AcCa(18:2)+H,AcCa(18:2)+H,AcCa,(18:2),(18:2),NaN,NaN,424.342135,424.34214,...,0.000000e+00,0.0000,3.829629e+04,1.074883e+06,2.467938e+06,2.583901e+06,3.904999e+06,9.525032e+05,1.144730e+06,1.083294e+06
8,9,AcCa(20:0)+H,AcCa(20:0)+H,AcCa,(20:0),(20:0),NaN,NaN,456.404735,456.40474,...,3.392261e+05,0.0000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
9,10,AcCa(20:1)+H,AcCa(20:1)+H,AcCa,(20:1),(20:1),NaN,NaN,454.389085,454.38909,...,3.092305e+05,0.0000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
11,12,AcCa(20:4)+H,AcCa(20:4)+H,AcCa,(20:4),(20:4),NaN,NaN,448.342135,448.34214,...,0.000000e+00,0.0000,2.128523e+05,1.397206e+06,1.275163e+06,1.641384e+06,2.815323e+06,8.866506e+05,4.808836e+05,5.184192e+05
13,14,AcCa(21:0)+H,AcCa(21:0)+H,AcCa,(21:0),(21:0),NaN,NaN,470.420385,470.42039,...,0.000000e+00,0.0000,3.601743e+05,1.431873e+06,2.263012e+06,2.678716e+06,3.317865e+06,1.802591e+06,1.434313e+06,9.803723e+05

In [19]:
df_positive_filtered.shape

(1238, 33)

In [ ]:
#option2
#df_sorted = df.sort_values(by='Rt', ascending=False)
#df_filt2 = df_sorted.drop_duplicates(subset='LipidIon', keep='first')

In [20]:
dataNegative = "CPLZ08292402-2_negative data.xlsx"
df_negative = pd.read_excel(dataNegative)

In [27]:
df_negative.head()

,No,LipidIon,LipidGroup,Class,FattyAcid,FA1,FA2,FA3,CalcMz,ObsMz,...,ED3,LW1,LW2,LW3,LN1,LN2,LN3,LE1,LE2,LE3
0,1,BiotinylPE(17:4)-H,BiotinylPE(17:4)-H,BiotinylPE,(17:4),(17:4),NaN,NaN,698.288181,698.28818,...,559819.3038,3.241879e+05,3.342377e+05,2.246472e+05,8.373872e+05,2.937244e+05,5.741149e+05,395338.3890,2035307.684,896728.6008
1,2,BiotinylPE(29:0)-H,BiotinylPE(29:0)-H,BiotinylPE,(29:0),(29:0),NaN,NaN,874.538581,874.53858,...,618727.2670,6.017536e+06,4.946070e+06,2.261614e+06,1.511098e+06,3.430637e+06,3.695453e+06,653465.1210,597509.164,760239.7230
2,3,BiotinylPE(31:0)-H,BiotinylPE(31:0)-H,BiotinylPE,(31:0),(31:0),NaN,NaN,902.569881,902.56988,...,180664.6750,5.179091e+06,3.355959e+06,1.741735e+06,9.502546e+05,2.516269e+06,3.005312e+06,96747.0420,123056.293,188371.5180
3,4,BiotinylPE(31:1)-H,BiotinylPE(31:1)-H,BiotinylPE,(31:1),(31:1),NaN,NaN,900.554231,900.55423,...,52905.1704,5.870855e+05,2.384036e+06,5.499062e+05,7.977391e+05,7.882101e+05,1.343165e+06,291677.8400,54838.158,248226.4311
4,5,BiotinylPE(31:2)-H,BiotinylPE(31:2)-H,BiotinylPE,(31:2),(31:2),NaN,NaN,898.538581,898.53858,...,60107.2071,1.807777e+06,2.400740e+06,1.134690e+06,5.280464e+05,8.625769e+05,1.180132e+06,170132.2401,35878.626,72317.0640

In [21]:
df_negative.shape

(1303, 33)

In [23]:
df_negative_filtered = df_negative.loc[df_negative.groupby('LipidIon')['Rt'].idxmax()]

In [25]:
df_negative_filtered.shape

(899, 33)

In [26]:
df_negative_filtered.head()

,No,LipidIon,LipidGroup,Class,FattyAcid,FA1,FA2,FA3,CalcMz,ObsMz,...,ED3,LW1,LW2,LW3,LN1,LN2,LN3,LE1,LE2,LE3
0,1,BiotinylPE(17:4)-H,BiotinylPE(17:4)-H,BiotinylPE,(17:4),(17:4),NaN,NaN,698.288181,698.28818,...,559819.3038,3.241879e+05,3.342377e+05,2.246472e+05,8.373872e+05,2.937244e+05,5.741149e+05,395338.3890,2035307.684,896728.6008
1,2,BiotinylPE(29:0)-H,BiotinylPE(29:0)-H,BiotinylPE,(29:0),(29:0),NaN,NaN,874.538581,874.53858,...,618727.2670,6.017536e+06,4.946070e+06,2.261614e+06,1.511098e+06,3.430637e+06,3.695453e+06,653465.1210,597509.164,760239.7230
2,3,BiotinylPE(31:0)-H,BiotinylPE(31:0)-H,BiotinylPE,(31:0),(31:0),NaN,NaN,902.569881,902.56988,...,180664.6750,5.179091e+06,3.355959e+06,1.741735e+06,9.502546e+05,2.516269e+06,3.005312e+06,96747.0420,123056.293,188371.5180
3,4,BiotinylPE(31:1)-H,BiotinylPE(31:1)-H,BiotinylPE,(31:1),(31:1),NaN,NaN,900.554231,900.55423,...,52905.1704,5.870855e+05,2.384036e+06,5.499062e+05,7.977391e+05,7.882101e+05,1.343165e+06,291677.8400,54838.158,248226.4311
4,5,BiotinylPE(31:2)-H,BiotinylPE(31:2)-H,BiotinylPE,(31:2),(31:2),NaN,NaN,898.538581,898.53858,...,60107.2071,1.807777e+06,2.400740e+06,1.134690e+06,5.280464e+05,8.625769e+05,1.180132e+06,170132.2401,35878.626,72317.0640

In [ ]:
pepo.to_csv("pepoTransposed.csv")
pepo = "pepoTransposed.csv"

In [75]:
MergedPositiveNegative_Lipidomics = pd.concat([df_positive_filtered,df_negative_filtered],
         ignore_index=True)

In [76]:
MergedPositiveNegative_Lipidomics.head()

,No,LipidIon,LipidGroup,Class,FattyAcid,FA1,FA2,FA3,CalcMz,ObsMz,...,ED3,LW1,LW2,LW3,LN1,LN2,LN3,LE1,LE2,LE3
0,1,AcCa(15:0)+H,AcCa(15:0)+H,AcCa,(15:0),(15:0),NaN,NaN,386.326485,386.32649,...,6.444122e+05,2321.1080,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
1,2,AcCa(16:0)+H,AcCa(16:0)+H,AcCa,(16:0),(16:0),NaN,NaN,400.342135,400.34214,...,0.000000e+00,0.0000,1.057062e+06,2.636818e+06,3.183084e+06,3.996716e+06,5.046420e+06,2.180633e+06,2.291380e+06,2.086173e+06
2,3,AcCa(17:1)+H,AcCa(17:1)+H,AcCa,(17:1),(17:1),NaN,NaN,412.342135,412.34214,...,1.137681e+06,163450.5650,0.000000e+00,4.140000e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
3,5,AcCa(18:0)+H,AcCa(18:0)+H,AcCa,(18:0),(18:0),NaN,NaN,428.373435,428.37344,...,0.000000e+00,3004.9536,4.654802e+06,1.275543e+07,1.668676e+07,2.053900e+07,2.078996e+07,1.459915e+07,1.601355e+07,1.255348e+07
4,6,AcCa(18:1)+H,AcCa(18:1)+H,AcCa,(18:1),(18:1),NaN,NaN,426.357785,426.35779,...,6.282316e+03,0.0000,5.214563e+06,1.381020e+07,1.670162e+07,2.051538e+07,2.759166e+07,1.006178e+07,1.101308e+07,1.130930e+07

In [64]:
MergedPositiveNegative_Lipidomics.tail()

,No,LipidIon,LipidGroup,Class,FattyAcid,FA1,FA2,FA3,CalcMz,ObsMz,...,ED3,LW1,LW2,LW3,LN1,LN2,LN3,LE1,LE2,LE3
2132,1299,dMePE(40:8+OO)-H,dMePE(40:8+OO)-H,dMePE,(40:8+OO),(40:8+OO),NaN,NaN,846.529061,846.52906,...,0.000000e+00,2.531559e+06,4.835344e+05,2.053372e+06,6.748116e+05,6.972259e+05,7.540934e+05,3.835034e+05,1.321995e+06,1.845150e+05
2133,1300,dMePE(44:1)-H,dMePE(44:1)-H,dMePE,(44:1),(44:1),NaN,NaN,884.711381,884.71138,...,2.898482e+05,1.487704e+06,1.241927e+06,4.028423e+05,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,4.031408e+05
2134,1301,phSM(d19:0_16:1)+HCOO,phSM(d35:1)+HCOO,phSM,(d19:0_16:1),(d19:0),(16:1),NaN,777.576345,777.57634,...,8.415979e+04,1.572032e+06,8.420498e+05,2.785517e+06,1.832359e+06,1.355600e+06,2.139183e+06,2.047917e+06,1.776615e+06,1.055186e+06
2135,1302,phSM(d19:0_18:1)+HCOO,phSM(d37:1)+HCOO,phSM,(d19:0_18:1),(d19:0),(18:1),NaN,805.607645,805.60764,...,1.475738e+06,1.197755e+07,6.660458e+06,1.526956e+07,1.022941e+07,1.220147e+07,1.233998e+07,1.301337e+07,1.146920e+07,8.587201e+06
2136,1303,phSM(t41:0)+HCOO,phSM(t41:0)+HCOO,phSM,(t41:0),(t41:0),NaN,NaN,879.680810,879.68081,...,2.060061e+06,1.864975e+07,1.163470e+07,2.152489e+07,1.994717e+07,1.877844e+07,2.106428e+07,4.632783e+07,3.952904e+07,3.509816e+07

In [77]:
MergedPositiveNegative_Lipidomics.shape

(2137, 33)

In [78]:
MergedPositiveNegative_Lipidomics.drop(columns=['QC_1', 'QC_2', 'QC_3'], inplace=True)

In [79]:
MergedPositiveNegative_Lipidomics.shape

(2137, 30)

In [80]:
MergedPositiveNegative_Lipidomics['LipidIon'].head(20)

0               AcCa(15:0)+H
1               AcCa(16:0)+H
2               AcCa(17:1)+H
3               AcCa(18:0)+H
4               AcCa(18:1)+H
5               AcCa(18:2)+H
6               AcCa(20:0)+H
7               AcCa(20:1)+H
8               AcCa(20:4)+H
9               AcCa(21:0)+H
10              AcCa(22:0)+H
11         BisMeLPA(14:0e)+H
12          BisMeLPA(8:0e)+H
13    BisMePA(10:1e_10:4)+Na
14    BisMePA(10:1e_12:1)+Na
15     BisMePA(10:1e_6:0)+Na
16        BisMePA(20:0e)+NH4
17    BisMePA(20:0e_15:0)+Na
18     BisMePA(20:0e_9:0)+Na
19        BisMePA(22:4e)+NH4
Name: LipidIon, dtype: object

In [73]:
MergedPositiveNegative_Lipidomics['LipidIon'] = MergedPositiveNegative_Lipidomics['LipidIon'].str.split('+').str[0]
MergedPositiveNegative_Lipidomics['LipidIon'].head(20)

0              AcCa(15:0)
1              AcCa(16:0)
2              AcCa(17:1)
3              AcCa(18:0)
4              AcCa(18:1)
5              AcCa(18:2)
6              AcCa(20:0)
7              AcCa(20:1)
8              AcCa(20:4)
9              AcCa(21:0)
10             AcCa(22:0)
11        BisMeLPA(14:0e)
12         BisMeLPA(8:0e)
13    BisMePA(10:1e_10:4)
14    BisMePA(10:1e_12:1)
15     BisMePA(10:1e_6:0)
16         BisMePA(20:0e)
17    BisMePA(20:0e_15:0)
18     BisMePA(20:0e_9:0)
19         BisMePA(22:4e)
Name: LipidIon, dtype: object

In [82]:
MergedPositiveNegative_Lipidomics.drop(columns=['FattyAcid',
                                                'No', 
                                                'Class',
                                                'FattyAcid',
                                                'FA1',
                                                'FA2',
                                                'FA3',
                                                'CalcMz',
                                                'ObsMz',
                                               ], inplace=True)

In [85]:
MergedPositiveNegative_Lipidomics.drop(columns=['IonFormula', 'Rt'], inplace=True)

In [89]:
MergedPositiveNegative_Lipidomics.head()

,LipidIon,EW1,EW2,EW3,EC1,EC2,EC3,ED1,ED2,ED3,LW1,LW2,LW3,LN1,LN2,LN3,LE1,LE2,LE3
0,AcCa(15:0)+H,5.244541e+05,357632.149,368598.253,890031.811,6.816787e+05,1283790.384,751813.249,371356.0560,6.444122e+05,2321.1080,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
1,AcCa(16:0)+H,1.014026e+04,0.000,0.227,0.000,0.000000e+00,10513.262,0.000,0.0000,0.000000e+00,0.0000,1.057062e+06,2.636818e+06,3.183084e+06,3.996716e+06,5.046420e+06,2.180633e+06,2.291380e+06,2.086173e+06
2,AcCa(17:1)+H,1.361606e+06,852211.532,753105.338,2557009.542,1.802111e+06,4590220.622,1959257.515,728377.5460,1.137681e+06,163450.5650,0.000000e+00,4.140000e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
3,AcCa(18:0)+H,0.000000e+00,0.000,0.000,0.000,0.000000e+00,0.000,0.000,0.0000,0.000000e+00,3004.9536,4.654802e+06,1.275543e+07,1.668676e+07,2.053900e+07,2.078996e+07,1.459915e+07,1.601355e+07,1.255348e+07
4,AcCa(18:1)+H,3.093196e+05,160511.070,208001.346,77223.302,1.675971e+04,20433.010,87059.748,4242.4998,6.282316e+03,0.0000,5.214563e+06,1.381020e+07,1.670162e+07,2.051538e+07,2.759166e+07,1.006178e+07,1.101308e+07,1.130930e+07

In [90]:
MergedPositiveNegative_Lipidomics.to_csv("LipidomicsFiltered.csv")